/* This file is part of the the dci project. Copyright (C) 2013-2023 vopl, shtoba.
   This program is free software: you can redistribute it and/or modify it under the terms of the GNU Affero General Public
   License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
   This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
   of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Affero General Public License for more details.
   You should have received a copy of the GNU Affero General Public License along with this program. If not, see <https://www.gnu.org/licenses/>. */

scope stiac::test
{

    interface AsArgument
    {
        in in_m();
        out out_m();
    }

    interface Base
    {
        in  in_m1(uint32 arg1) -> uint64;
    }

    interface Victim : Base
    {
        in  in_withResult() -> none;
        in  in_withResult2() -> uint32;

        out out_m1(string arg1, bool arg2) -> string;

        in  in_m2(AsArgument arg1);
    }
}
